GKI: device_snapshot: add wait for display
Wait for Boot Complete notification.

Signed-off-by: Mark Salyzyn <salyzyn@google.com>
Test: confirm screen active before script exit
Bug: 147894928
Change-Id: Id174733c30634d24b9ce85056cfe1aa02b13af6c

diff --git a/gki/device_snapshot b/gki/device_snapshot
--- a/gki/device_snapshot
+++ b/gki/device_snapshot
@@ -5,11 +5,13 @@
 
 progname=${0##*/}
 NUM=XX
-USAGE="USAGE: ${progname} [-s <serialno>] [-f [<input>]] [-o <output> [-d <input>]]
+USAGE="USAGE: ${progname} [-s <serialno>] [-D] [-f [<input>]] [-o <output> [-d <input>]]
 
 Collect filtered /dev and /sys details, along with dmesg and probe list.
 
 -o <output> will drop the collection into a set of files.
+
+-D will wait for the display.
 
 if <output> is empty ('' or last option), will not collect dmesg or probe
 list.  If no -o option is specified, then <output> will be default of -
@@ -73,7 +75,6 @@ inFastboot() {
     fi
 }
 
-
 [ "USAGE: inAdb
 
 Returns: true if device is in adb mode" ]
@@ -121,6 +122,42 @@ usb_devnum() {
     fi
     echo "${USB_DEVICE}"
   fi
+}
+
+[ "USAGE: adb_sh <commands> </dev/stdin >/dev/stdout 2>/dev/stderr
+
+Returns: true if the command succeeded" ]
+adb_sh() {
+  local args=
+  for i in "${@}"; do
+    [ -z "${args}" ] || args="${args} "
+    if [ X"${i}" != X"${i#\'}" ]; then
+      args="${args}${i}"
+    elif [ X"${i}" != X"${i#*\\}" ]; then
+      args="${args}`echo ${i} | sed 's/\\\\/\\\\\\\\/g'`"
+    elif [ X"${i}" != X"${i#* }" ]; then
+      args="${args}'${i}'"
+    elif [ X"${i}" != X"${i#*${TAB}}" ]; then
+      args="${args}'${i}'"
+    else
+      args="${args}${i}"
+    fi
+  done
+  adb shell "${args}"
+}
+
+[ "USAGE: adb_su <commands> </dev/stdin >/dev/stdout 2>/dev/stderr
+
+Returns: true if the command running as root succeeded" ]
+adb_su() {
+  adb_sh su root "${@}"
+}
+
+[ "USAGE: get_property <prop>
+
+Returns the property value" ]
+get_property() {
+  adb_sh getprop ${1} 2>/dev/null </dev/null
 }
 
 [ "USAGE: format_duration [<seconds>|<seconds>s|<minutes>m|<hours>h|<days>d]
@@ -300,6 +337,7 @@ any_wait() {
 filter=
 output=-
 input=
+display=false
 while [ ${#} -gt 0 ]; do
   case ${1} in
     -f=* | --filter=*)
@@ -338,6 +376,9 @@ while [ ${#} -gt 0 ]; do
     -d | --diff)
       shift
       input="${1}"
+      ;;
+    -D | --wait-for-display)
+      display=true
       ;;
     -s=* | --serial=*)
       ANDROID_SERIAL="${1#-s=}"
@@ -383,22 +424,39 @@ if [ -z "${filter}" ]; then
   fi
   if ! inAdb; then
     any_wait 2m
-    if [ -n "${ANDROID_SERIAL}" ]; then
-      echo "${RED}[    ERROR ]${NORMAL} not in adb mode" >&2
+    if ! inAdb; then
+      if [ -n "${ANDROID_SERIAL}" ]; then
+        echo "${RED}[    ERROR ]${NORMAL} not in adb mode" >&2
+        exit 1
+      fi
+      COUNT=`adb devices </dev/null |
+               grep -v -e 'List of devices attached' -e '^$' |
+               wc -l`
+      echo "${RED}[    ERROR ]${NORMAL} ${COUNT} devices attached" >&2
       exit 1
     fi
-    COUNT=`adb devices </dev/null |
-             grep -v -e 'List of devices attached' -e '^$' |
-             wc -l`
-    echo "${RED}[    ERROR ]${NORMAL} ${COUNT} devices attached" >&2
-    exit 1
   fi
+  counter=0
+  while ${display}; do
+    if inFastboot; then
+      fastboot reboot
+    elif inAdb; then
+      if [ "1" = "`get_property sys.boot_completed`" ]; then
+        break
+      fi
+    fi
+    counter=$((${counter} + 1))
+    if [ ${counter} -gt 120 ]; then
+      break
+    fi
+    sleep 1
+  done
 fi
 
 if [ -n "${filter}" ]; then
   cat ${filter}
 else
-  adb shell su root find /dev /sys </dev/null 2>/dev/null |
+  adb_su find /dev /sys </dev/null 2>/dev/null |
   if [ -n "${output}" -a X"${output}" != X"-" ]; then
     # Generate ${output}.probed:
     #
@@ -440,7 +498,7 @@ else
           *)
             INSTANCE="${driver#/sys/devices/platform/}"
             INSTANCE="${INSTANCE%/driver}"
-            DRIVER="`adb shell su root ls -l ${driver} </dev/null 2>/dev/null |
+            DRIVER="`adb_su ls -l ${driver} </dev/null 2>/dev/null |
                      sed -n 's@.* -> .*/bus/\([^/]*\)/drivers/\(.*\)@driver:\1:\2@p'`"
             if [ -z "${DRIVER}" ]; then
               echo "${INSTANCE}"
@@ -457,9 +515,9 @@ else
         esac
       done >"${output}.probed"
     # Generate ${output}.dmesg
-    adb shell su root dmesg </dev/null 2>/dev/null >"${output}.dmesg"
+    adb_su dmesg </dev/null 2>/dev/null >"${output}.dmesg"
     # Generate ${output}.config if kernel provides it.
-    adb shell su root cat /proc/config.gz </dev/null 2>/dev/null |
+    adb_su cat /proc/config.gz </dev/null 2>/dev/null |
       gunzip >"${output}.config"
     [ -s "${output}.config" ] || rm -f "${output}.config"
   else
@@ -544,7 +602,7 @@ fi |
   fi
 if [ -z "${filter}" -a X"${output}" = X"-" ]; then
   echo "------------------------> cut dmesg <------------------------"
-  adb shell su root dmesg </dev/null 2>/dev/null
+  adb_su dmesg </dev/null 2>/dev/null
   echo "-----------------------> cut .config <-----------------------"
-  adb shell su root cat /proc/config.gz </dev/null 2>/dev/null | gunzip
+  adb_su cat /proc/config.gz </dev/null 2>/dev/null | gunzip
 fi
