compare_to_symbol_list: add instructions to fix missing symbol
Add a goto link and reference to the build/abi/README.md to the error
message that detects missing symbols.

Change-Id: I6bc0f2a0985b4ee3376cabd526bcc3ba86d84a87
Signed-off-by: Will McVicker <willmcvicker@google.com>
Bug: 161911837

diff --git a/abi/compare_to_symbol_list b/abi/compare_to_symbol_list
--- a/abi/compare_to_symbol_list
+++ b/abi/compare_to_symbol_list
@@ -44,6 +44,8 @@ delta=$(diff -u $ksymtab $symbollist | grep -v ' ')
 rm $ksymtab $symbollist
 if [ -n "$delta" ]; then
 	echo "ERROR: Differences between ksymtab and symbol list detected!" >&2
+	echo "ERROR: Refer to go/gki-symbol-list-update for steps to fix this" >&2
+	echo "ERROR:    or to build/abi/README.md#6_working-with-symbol-lists." >&2
 	echo "Symbols missing from ksymtab:" >&2
 	echo "$delta" | sed -n -e 's/^+/ - /p' >&2
 	echo "Symbols missing from symbol list:" >&2
